[build]
builder = "nixpacks"
watchPatterns = ["*.py"]
buildCommand = "pip install -r requirements.txt" 

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT --workers=2"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
